name: Parallel test build
on: push
jobs:
  Add-To-Cart-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:runCheckout

      - name: Cypress report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome-reports-1
          path: cypress/reports/html

  Login-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:runLoginCheck

      - name: Cypress report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome-reports-2
          path: cypress/reports/html
